## Preprocessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

dataset=pd.read_csv("/content/drive/My Drive/Colab Notebooks/Datasets/loan_small.csv")

In [ ]:
dataset.head()

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y

In [ ]:
 dataset.isnull().sum()

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64

In [ ]:
dataset.shape

(16, 7)

In [ ]:
dataset.ndim

2

In [ ]:
# filling missing values
# dataset=dataset.dropna()

In [ ]:
dt=dataset.copy()

In [ ]:
dt

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
cols=["Gender","Area","Loan_Status"]

In [ ]:
dt.mode().iloc[0]

Loan_ID              LP001002
Gender                   Male
ApplicantIncome        1299.0
CoapplicantIncome         0.0
LoanAmount               17.0
Area                     semi
Loan_Status                 Y
Name: 0, dtype: object

In [ ]:
dt[cols]=dt[cols].fillna(dt.mode().iloc[0])

In [ ]:
dt

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,Male,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,semi,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
cols2=["ApplicantIncome","CoapplicantIncome","LoanAmount"]
dt[cols2]=dt[cols2].fillna(dt[cols2].mean())

In [ ]:
dt

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,Male,5849.000000,0.000000,140.923077,urban,Y
1,LP001003,Male,4583.000000,2509.333333,128.000000,semi,N
2,LP001005,Male,3000.000000,0.000000,66.000000,semi,Y
3,LP001006,Female,2583.000000,2358.000000,120.000000,semi,Y
4,LP001008,Male,4103.571429,0.000000,141.000000,urban,Y
5,LP001011,Male,5417.000000,4196.000000,267.000000,semi,Y
6,LP001013,Male,2333.000000,1516.000000,140.923077,rural,Y
7,LP001014,Female,3036.000000,2504.000000,158.000000,semi,N
8,LP001018,Male,4006.000000,1526.000000,168.000000,rural,Y
9,LP001020,Male,12841.000000,10968.000000,349.000000,semi,N
10,LP001024,Female,3200.000000,700.000000,70.000000,urban,Y
11,LP001027,Male,2500.000000,1840.000000,109.000000,urban,Y
12,LP001028,Female,4103.571429,8106.000000,140.923077,urban,Y
13,LP001029,Male,1853.000000,2840.000000,114.000000,urban,N
14,LP001030,Male,1299.000000,1086.000000,17.000000,semi,Y
15,LP001032,Male,4950.000000,0.000000,125.000000,semi,Y

In [ ]:
# converting datatype

In [ ]:
dt.dtypes

Loan_ID               object
Gender                object
ApplicantIncome      float64
CoapplicantIncome    float64
LoanAmount           float64
Area                  object
Loan_Status           object
dtype: object

In [ ]:
dt[cols]=dt[cols].astype('category')

In [ ]:
dt.dtypes

Loan_ID                object
Gender               category
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount            float64
Area                 category
Loan_Status          category
dtype: object

In [ ]:
# converting categorical to numerical

In [ ]:
for column in cols:
    dt[column]=dt[column].cat.codes

In [ ]:
dt

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,1,5849.000000,0.000000,140.923077,2,1
1,LP001003,1,4583.000000,2509.333333,128.000000,1,0
2,LP001005,1,3000.000000,0.000000,66.000000,1,1
3,LP001006,0,2583.000000,2358.000000,120.000000,1,1
4,LP001008,1,4103.571429,0.000000,141.000000,2,1
5,LP001011,1,5417.000000,4196.000000,267.000000,1,1
6,LP001013,1,2333.000000,1516.000000,140.923077,0,1
7,LP001014,0,3036.000000,2504.000000,158.000000,1,0
8,LP001018,1,4006.000000,1526.000000,168.000000,0,1
9,LP001020,1,12841.000000,10968.000000,349.000000,1,0
10,LP001024,0,3200.000000,700.000000,70.000000,2,1
11,LP001027,1,2500.000000,1840.000000,109.000000,2,1
12,LP001028,0,4103.571429,8106.000000,140.923077,2,1
13,LP001029,1,1853.000000,2840.000000,114.000000,2,0
14,LP001030,1,1299.000000,1086.000000,17.000000,1,1
15,LP001032,1,4950.000000,0.000000,125.000000,1,1

In [ ]:
df2=dataset.drop(['Loan_ID'],axis=1)

In [ ]:
df2=pd.get_dummies(df2)

In [ ]:
df2

,ApplicantIncome,CoapplicantIncome,LoanAmount,Gender_Female,Gender_Male,Area_rural,Area_semi,Area_urban,Loan_Status_N,Loan_Status_Y
0,5849.0,0.0,NaN,False,False,False,False,True,False,True
1,4583.0,NaN,128.0,False,True,False,True,False,True,False
2,3000.0,0.0,66.0,False,True,False,False,False,False,True
3,2583.0,2358.0,120.0,True,False,False,True,False,False,False
4,NaN,0.0,141.0,False,True,False,False,True,False,True
5,5417.0,4196.0,267.0,False,True,False,True,False,False,True
6,2333.0,1516.0,NaN,False,True,True,False,False,False,True
7,3036.0,2504.0,158.0,True,False,False,True,False,True,False
8,4006.0,1526.0,168.0,False,True,True,False,False,False,True
9,12841.0,10968.0,349.0,False,True,False,True,False,True,False
10,3200.0,700.0,70.0,True,False,False,False,True,False,True
11,2500.0,1840.0,109.0,False,True,False,False,True,False,True
12,NaN,8106.0,NaN,True,False,False,False,True,False,True
13,1853.0,2840.0,114.0,False,True,False,False,True,True,False
14,1299.0,1086.0,17.0,False,True,False,True,False,False,True
15,4950.0,0.0,125.0,False,True,False,True,False,False,True

In [ ]:
#data normalisatioon

In [ ]:
dataset2=dataset.dropna()

In [ ]:
dataset2

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
data_to_scale=dataset2.iloc[:,2:5]

In [ ]:
data_to_scale

    ApplicantIncome  CoapplicantIncome  LoanAmount
5            5417.0             4196.0       267.0
7            3036.0             2504.0       158.0
8            4006.0             1526.0       168.0
9           12841.0            10968.0       349.0
10           3200.0              700.0        70.0
11           2500.0             1840.0       109.0
13           1853.0             2840.0       114.0
14           1299.0             1086.0        17.0
15           4950.0                0.0       125.0

In [ ]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [ ]:
s_scaler=StandardScaler()

In [ ]:
ss_scaler=s_scaler.fit_transform(data_to_scale)

In [ ]:
ss_scaler

array([[ 0.32879835,  0.43390231,  1.1995349 ],
       [-0.40126276, -0.11198867,  0.05261118],
       [-0.10384182, -0.4275214 ,  0.15783354],
       [ 2.60514177,  2.61875676,  2.06235824],
       [-0.35097716, -0.69401428, -0.87334558],
       [-0.56561083, -0.32621539, -0.46297838],
       [-0.76399367, -0.00358478, -0.4103672 ],
       [-0.9338609 , -0.56947886, -1.43102409],
       [ 0.18560703, -0.9198557 , -0.29462261]])

In [ ]:

m_scaler=MinMaxScaler()

In [ ]:
mm_scaler=m_scaler.fit_transform(data_to_scale)

In [ ]:
mm_scaler

array([[0.35678392, 0.38256747, 0.75301205],
       [0.15049385, 0.22830051, 0.4246988 ],
       [0.23453474, 0.13913202, 0.45481928],
       [1.        , 1.        , 1.        ],
       [0.16470282, 0.06382203, 0.15963855],
       [0.10405476, 0.16776076, 0.27710843],
       [0.04799861, 0.25893508, 0.29216867],
       [0.        , 0.09901532, 0.        ],
       [0.31632299, 0.        , 0.3253012 ]])

In [ ]:
x=dt.iloc[:,1:-1]

In [ ]:
y=dt.iloc[:,-1:]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
std_reg=LinearRegression()

In [ ]:
std_reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=std_reg.predict(x_test)

In [ ]:
y_pred

array([[1.18799152],
       [0.64395662],
       [0.90779438],
       [2.39938573]])

In [ ]:
y_test

   Loan_Status
1            0
6            1
8            1
9            0

In [ ]:
std_reg.coef_

array([[ 1.25709936e-01,  2.41566172e-04,  4.31750847e-05,
        -5.19756965e-03, -1.09544826e-01]])

In [ ]:
std_reg.intercept_

array([0.62167688])