### *Importing Libraries*

In [1]:
import pandas as pd
import numpy as np

### *Load Dataset*

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
dataset=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/loan_data.csv')
df=dataset.copy()

### *Summarize Dataset*

In [4]:
df.shape

(614, 6)

In [5]:
df.head()

  gender married   ch  income  loanamt status
0   Male      No  1.0    5849      NaN      Y
1   Male     Yes  1.0    4583    128.0      N
2   Male     Yes  1.0    3000     66.0      Y
3   Male     Yes  1.0    2583    120.0      Y
4   Male      No  1.0    6000    141.0      Y

In [6]:
df.isnull().sum()

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [7]:
df.dtypes

gender      object
married     object
ch         float64
income       int64
loanamt    float64
status      object
dtype: object

## Preprocessing

In [8]:
cols=['ch','loanamt']
df[cols]=df[cols].fillna(df[cols].mean())

In [9]:
df.isnull().sum()

gender     13
married     3
ch          0
income      0
loanamt     0
status      0
dtype: int64

In [10]:
df['married']=df['married'].fillna(df.mode().iloc[0])

In [11]:
df=df.drop(['gender'],axis=1)

In [12]:
df.head()

  married   ch  income     loanamt status
0      No  1.0    5849  146.412162      Y
1     Yes  1.0    4583  128.000000      N
2     Yes  1.0    3000   66.000000      Y
3     Yes  1.0    2583  120.000000      Y
4      No  1.0    6000  141.000000      Y

In [13]:
df=pd.get_dummies(df,drop_first=True)

In [14]:
df

      ch  income     loanamt  married_Yes  status_Y
0    1.0    5849  146.412162        False      True
1    1.0    4583  128.000000         True     False
2    1.0    3000   66.000000         True      True
3    1.0    2583  120.000000         True      True
4    1.0    6000  141.000000        False      True
..   ...     ...         ...          ...       ...
609  1.0    2900   71.000000        False      True
610  1.0    4106   40.000000         True      True
611  1.0    8072  253.000000         True      True
612  1.0    7583  187.000000         True      True
613  0.0    4583  133.000000        False     False

[614 rows x 5 columns]

## Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [16]:
df['income']=scaler.fit_transform(df[['income']])
df['loanamt']=scaler.fit_transform(df[['loanamt']])

In [17]:
df.head()

    ch    income   loanamt  married_Yes  status_Y
0  1.0  0.072991  0.000000        False      True
1  1.0 -0.134412 -0.219273         True     False
2  1.0 -0.393747 -0.957641         True      True
3  1.0 -0.462062 -0.314547         True      True
4  1.0  0.097728 -0.064454        False      True

### *Segregate Dataset into X(Input/IndependentVariable) & Y(Output/DependentVariable)*

In [18]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [22]:
x

array([[1.0, 0.07299082285068836, 0.0, False],
       [1.0, -0.13441195378345122, -0.21927331495275867, True],
       [1.0, -0.3937473372051281, -0.9576409986248737, True],
       ...,
       [1.0, 0.437174371395469, 1.2693712085797315, True],
       [1.0, 0.35706382023109756, 0.4833669001545767, True],
       [0.0, -0.13441195378345122, -0.15972753401145906, False]],
      dtype=object)

In [23]:
y

array([ True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True, False, False, False,  True,  True,
        True, False,  True, False, False, False,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False,  True,  True, False,  True,  True,
        True, False,  True, False, False, False, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
       False, False,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False,  True, False,
       False, False,  True, False,  True,  True, False,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False, False,
        True,  True, False,  True, False, False, False, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True, False, False,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True, False,
        True,  True,  True, False, False, False,  True, False,  True,
       False,  True, False, False,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False, False,  True,  True, False, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True, False,  True, False, False,  True,
       False,  True,  True,  True,  True, False,  True, False, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False])

### *Splitting Dataset into Train & Test*

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

### *Training*

In [20]:
from sklearn.svm import SVC
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)

SVC()

### *Prediction for all Test Data*

In [21]:
c1=float(input("enter first col"))
c2=float(input("enter income"))
c3=float(input("enter  loan amount"))
c4=int(input("enter married or not"))

KeyboardInterrupt: Interrupted by user

In [ ]:
c2=scaler.transform([[c2]])
c3=scaler.transform([[c3]])

In [ ]:
# prompt: predict using user entered data

new_data = [[c1, c2[0][0], c3[0][0], c4]]
y_pred = svc.predict(new_data)

print("Prediction:", y_pred)

In [ ]:
print(svc.predict(data))

In [ ]:
y_pred=svc.predict(x_test)

### *Evaluating Model*

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

In [ ]:
print(svc.score(x_test,y_test))